services:
  - type: web
    name: openf1-mcp
    runtime: node
    plan: free
    buildCommand: npm run build
    startCommand: npm run start:http
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000